### ISSUE TITLE
MaxPool3d error when converted to onnx

### ISSUE THREAD

**Issue by cxmscb** [hunto/LightViT#3]
Name:'MaxPool_644' Status Message: pool.cc:127 onnxruntime::PoolBase::Compute kernel_shape num_dims is not compatible with X num_dims.

**Comment by hunto** [comment]
Hi @cxmscb, 

The `x` in [lightvit.py#L299](https://github.com/hunto/image_classification_sota/blob/36539b63cc8b851bd3fc93251bba60528813bb36/lib/models/lightvit.py#L299) is with shape `[B, H, W, C]`. In our implementation, to avoid permutations of tensor, we use a MaxPool3d operation with the kernel size `1` at the last dimension (C).

Actually the operation can be replaced with a MaxPool2d operation, as the following sample:
```python
def __init__(...):
    ...
    self.maxp = nn.MaxPool2d(2, 2)
    ...

def forward(...):
    ...
    res = self.maxp(x.permute(0, 3, 1, 2)).permute(0, 2, 3, 1)
    res = self.res_proj(res.view(B, -1, C))
    ...
```

You can try this and see whether this works for onnx.
