### ISSUE TITLE
mc module

### ISSUE THREAD

**Issue by kunsaram01** [hunto/LightViT#4]
Hi, I am trying to train lightvit tiny model, but I faced this issue. 
What is the `mc module` that you mentioned in the code? 

> bash tools/dist_train.sh 2 configs/strategies/lightvit/config.yaml timm_lightvit_tiny --drop-path-rate 0.1 --experiment lightvit_tiny
> 
> python -m torch.distributed.launch --nproc_per_node=2 tools/train.py -c configs/strategies/lightvit/config.yaml --model timm_lightvit_tiny --drop-path-rate 0.1 --experiment lightvit_tiny
> 
> /home/cvlab/anaconda3/envs/lightvit2/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torchrun.
> Note that --use_env is set by default in torchrun.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See 
> https://pytorch.org/docs/stable/distributed.html#launch-utility for 
> further instructions
> 
>   warnings.warn(
> WARNING:torch.distributed.run:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> /home/cvlab/projects/image_classification_sota/lib/dataset/dataset.py:12: UserWarning: mc module not found, using original Image.open to read images
>   warnings.warn('mc module not found, using original '
> /home/cvlab/projects/image_classification_sota/lib/dataset/dataset.py:12: UserWarning: mc module not found, using original Image.open to read images
>   warnings.warn('mc module not found, using original '
>

**Comment by hunto** [comment]
Hi @kunsaram01 , 

It seems like your training can be successfully launched with some ignorable warnings.

The `mc` module is an internal extension in our training environment, and it is a memorycache system which can reduce the data loading time by reading images from the memory.

It is OK for you to running the code without this extension, and the images will be read from your disk, which is the default way in torchvision's training example.

If you have other questions, please don't hesitate to ask us for help.
