### ISSUE TITLE
about ckpt model

### ISSUE THREAD

**Issue by dydxdt** [hunto/LightViT#5]
您好，请问下为什么提供的训练好的模型是ckpt文件，不是pth文件？是用tf训练的吗？并且在轻量化上，LightViT可能主要对比的结构是transformer一类，而不是mobilenet等常用的轻量级网络？因为自己训练出的LightViT-small模型有200多M。谢谢～

**Comment by hunto** [comment]
Hi @dydxdt ,

模型文件是用pytorch训练及存储的，后缀名不会影响文件内容。LightViT更关注FLOPs、inference latency和精度，不注重减小模型参数量。
